### ISSUE TITLE
eth_gasPrice crash

### ISSUE THREAD

**Issue by lebdron** [ava-labs/coreth#174]
Using the default settings, `eth_gasPrice` crashes with the following trace
```
ERROR[12-10|16:40:35.051] RPC method eth_gasPrice crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 139 [running]:
github.com/ava-labs/coreth/rpc.(*callback).call.func1(0xc0015e0790, 0xc, 0xc001565cc0)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/rpc/service.go:210 +0xbd
panic(0xf3c840, 0x18b2c00)
        /home/ubuntu/install/go1.16.8/src/runtime/panic.go:965 +0x1b9
math/big.(*Int).Cmp(0xc0015a2300, 0x0, 0xc001636440)
        /home/ubuntu/install/go1.16.8/src/math/big/int.go:328 +0x44
github.com/ethereum/go-ethereum/common/math.BigMin(...)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.12/common/math/big.go:148
github.com/ava-labs/coreth/eth/gasprice.(*Oracle).SuggestPrice(0xc00014c6c0, 0x1327c78, 0xc001636440, 0xc0012d58d0, 0x4c6e8b, 0xf6ba80)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/eth/gasprice/gasprice.go:224 +0x1d1
github.com/ava-labs/coreth/eth.(*EthAPIBackend).SuggestPrice(0xc001480558, 0x1327c78, 0xc001636440, 0x30, 0x7f11b380d5b8, 0x30)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/eth/api_backend.go:357 +0x45
github.com/ava-labs/coreth/internal/ethapi.(*PublicEthereumAPI).GasPrice(0xc0010fe910, 0x1327c78, 0xc001636440, 0x0, 0x0, 0x0)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/internal/ethapi/api.go:71 +0x4e
reflect.Value.call(0xc0014fe2a0, 0xc00009f850, 0x13, 0x1082042, 0x4, 0xc001654b70, 0x2, 0x2, 0xc0012d5b58, 0x46a08c, ...)
        /home/ubuntu/install/go1.16.8/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0014fe2a0, 0xc00009f850, 0x13, 0xc001654b70, 0x2, 0x2, 0x1312100, 0xc000032080, 0xc002420000)
        /home/ubuntu/install/go1.16.8/src/reflect/value.go:337 +0xb9
github.com/ava-labs/coreth/rpc.(*callback).call(0xc0014fe420, 0x1327c78, 0xc001636440, 0xc0015e0790, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/rpc/service.go:216 +0x2c5
github.com/ava-labs/coreth/rpc.(*handler).runMethod(0xc00055e640, 0x1327c78, 0xc001636440, 0xc0004f7260, 0xc0014fe420, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/rpc/handler.go:486 +0x8a
github.com/ava-labs/coreth/rpc.(*handler).handleCall(0xc00055e640, 0xc0015eb680, 0xc0004f7260, 0x1000000426d9b)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/rpc/handler.go:434 +0x265
github.com/ava-labs/coreth/rpc.(*handler).handleCallMsg(0xc00055e640, 0xc0015eb680, 0xc0004f7260, 0xc0015eb680)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/rpc/handler.go:395 +0x212
github.com/ava-labs/coreth/rpc.(*handler).handleMsg.func1(0xc0015eb680)
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/rpc/handler.go:167 +0x46
github.com/ava-labs/coreth/rpc.(*handler).startCallProc.func1()
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/rpc/handler.go:307 +0x1e2
created by github.com/ava-labs/coreth/rpc.(*handler).startCallProc
        /home/ubuntu/install/avalanche/go/pkg/mod/github.com/ava-labs/coreth@v0.8.2-rc.0/rpc/handler.go:311 +0xa5

WARN [12-10|16:40:35.051] Served eth_gasPrice                      reqid=1 execTime="165.863µs" procTime="166.486µs" totalTime="166.77µs" err="method handler crashed"
```

**Comment by aaronbuchwald** [comment]
Thanks for creating this issue @lebdron . We have a fix ready that will go out in the next release. Out of curiosity, did you observe this error running your own mainnet node?

**Comment by lebdron** [comment]
Aaron,

No, I created a private network using the master branch of Avalanche.

Andrei

**Comment by aaronbuchwald** [comment]
Great, this actually explains something that I was a bit confused about. What are you using as the genesis for this network?

**Comment by lebdron** [comment]
```
{
  "networkID":1337,
  "allocations":[
    {
      "ethAddr":"0x0000000000000000000000000000000000000000",
      "avaxAddr":"X-custom1859dz2uwazfgahey3j53ef2kqrans0c8lah5pq",
      "initialAmount":0,
      "unlockSchedule":[
        {
          "amount":2000000000000000,
          "locktime":0
        }
      ]
    }
  ],
  "startTime":1639177273,
  "initialStakeDuration":31536000,
  "initialStakeDurationOffset":5400,
  "initialStakedFunds":[
    "X-custom1859dz2uwazfgahey3j53ef2kqrans0c8lah5pq"
  ],
  "initialStakers":[
    {
      "nodeID":"NodeID-Bh2on2WNgUqn493y63ZWXKDrZqcznDCa5",
      "rewardAddress":"X-custom1ayp2n2rxgzlak8xsudkqejvzhql9we06r26mwl",
      "delegationFee":10000
    },
    {
      "nodeID":"NodeID-6TNKGfYTVGXuN7ZTzfS5juWcHMk969uLQ",
      "rewardAddress":"X-custom1ayp2n2rxgzlak8xsudkqejvzhql9we06r26mwl",
      "delegationFee":10000
    }
  ],
  "cChainGenesis":"{\"alloc\":{\"0x002caecfc71369c50212b4990ae74de64d708d95\":{\"balance\":\"0x118427b3b4a05bc8a8a4de845986800000000000\"}},\"coinbase\":\"0x0000000000000000000000000000000000000000\",\"config\":{\"apricotPhase1BlockTimestamp\":0,\"apricotPhase2BlockTimestamp\":0,\"byzantiumBlock\":0,\"chainId\":43115,\"constantinopleBlock\":0,\"daoForkBlock\":0,\"daoForkSupport\":true,\"eip150Block\":0,\"eip150Hash\":\"0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0\",\"eip155Block\":0,\"eip158Block\":0,\"homesteadBlock\":0,\"istanbulBlock\":0,\"muirGlacierBlock\":0,\"petersburgBlock\":0},\"difficulty\":\"0x0\",\"extraData\":\"0x00\",\"gasLimit\":\"0x5f5e100\",\"gasUsed\":\"0x0\",\"mixHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"nonce\":\"0x0\",\"number\":\"0x0\",\"parentHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"timestamp\":\"0x0\"}",
  "message":"hello world"
}
```
