### ISSUE TITLE
Fix `panic: close of closed channel` produced by tests in `plugin/evm`

### ISSUE THREAD

**Issue by qdm12** [ava-labs/coreth#725]
[Github action run](https://github.com/ava-labs/coreth/actions/runs/12550054659/job/34992169636?pr=721)

Relevant logs in case the action run gets deleted:

```
-test.shuffle 1735581512442363633
{"timestamp":"2024-12-30T17:59:57.006609157Z","level":"info","msg":"test","logger":"alias Chain","caller":"plugin/evm/log_test.go:32"}
{"timestamp":"2024-12-30T17:59:57.008486795Z","level":"info","msg":"Persisted trie from memory database","nodes":3,"size":"403.00 B","time":"59.682µs","gcnodes":0,"gcsize":"0.00 B","gctime":"0s","livenodes":0,"livesize":"0.00 B","logger":"alias Chain","caller":"triedb/hashdb/database.go:546"}
{"timestamp":"2024-12-30T17:59:57.009519199Z","level":"info","msg":"Persisted trie from memory database","nodes":3,"size":"403.00 B","time":"54.031µs","gcnodes":0,"gcsize":"0.00 B","gctime":"0s","livenodes":0,"livesize":"0.00 B","logger":"alias Chain","caller":"triedb/hashdb/database.go:546"}
panic: close of closed channel

goroutine 20106 [running]:
github.com/ava-labs/coreth/sync/statesync.(*stateSync).onStorageTrieFinished(0xc0093be1a0, {0xfd, 0x4b, 0x68, 0x[77](https://github.com/ava-labs/coreth/actions/runs/12550054659/job/34992169636?pr=721#step:10:78), 0xdb, 0x90, 0x8, 0xa4, 0xa5, ...})
	/home/runner/work/coreth/coreth/sync/statesync/state_syncer.go:128 +0x17b
github.com/ava-labs/coreth/sync/statesync.(*storageTrieTask).OnFinish(0xc00db54680)
	/home/runner/work/coreth/coreth/sync/statesync/trie_sync_tasks.go:139 +0x85
github.com/ava-labs/coreth/sync/statesync.(*trieToSync).segmentFinished(0xc00ab16210, {0x29e35[78](https://github.com/ava-labs/coreth/actions/runs/12550054659/job/34992169636?pr=721#step:10:79), 0xc00c8feeb0}, 0x0)
	/home/runner/work/coreth/coreth/sync/statesync/trie_segments.go:238 +0xaf1
github.com/ava-labs/coreth/sync/statesync.(*trieSegment).OnFinish(0xc012b3f260, {0x29e3578, 0xc00c8feeb0})
	/home/runner/work/coreth/coreth/sync/statesync/trie_segments.go:350 +0x75
github.com/ava-labs/coreth/sync/client.(*CallbackLeafSyncer).syncTask(0xc012aab0b0, {0x29e3578, 0xc00c8feeb0}, {0x29ed378, 0xc012b3f260})
	/home/runner/work/coreth/coreth/sync/client/leaf_syncer.go:136 +0x73d
github.com/ava-labs/coreth/sync/client.(*CallbackLeafSyncer).workerLoop(0xc012aab0b0, {0x29e3578, 0xc00c8feeb0})
	/home/runner/work/coreth/coreth/sync/client/leaf_syncer.go:71 +0x135
github.com/ava-labs/coreth/sync/client.(*CallbackLeafSyncer).Start.func1()
	/home/runner/work/coreth/coreth/sync/client/leaf_syncer.go:156 +0x47
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x92
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 199[80](https://github.com/ava-labs/coreth/actions/runs/12550054659/job/34992169636?pr=721#step:10:81)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x125
FAIL	github.com/ava-labs/coreth/plugin/evm	115.252s
```

**Comment by michaelkaplan13** [comment]
Closing this issue since it hasn't been reported again and the logs from the original failure are no longer available.
