### ISSUE TITLE
RPC Segfault

### ISSUE THREAD

**Issue by sosedoff** [ava-labs/coreth#84]
Got a few sigfaults while on testnet. Running avalanchego 1.1.0 / coreth 0.3.18 (on client).

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5d4ef0]

goroutine 747615 [running]:
bufio.(*Writer).Available(...)
	/usr/local/go/src/bufio/bufio.go:624
bufio.(*Writer).Write(0x0, 0x1b682b8, 0x2, 0x2, 0x4212, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:634 +0x70
net/http.(*chunkWriter).Write(0xc00400a660, 0xc000a34800, 0x4212, 0x4800, 0x7510c9, 0xc00339aee8, 0x0)
	/usr/local/go/src/net/http/server.go:385 +0x151
bufio.(*Writer).Write(0xc008480c00, 0xc000a34800, 0x4212, 0x4800, 0xc000a30000, 0x4248, 0x4248)
	/usr/local/go/src/bufio/bufio.go:639 +0x13d
net/http.(*response).write(0xc00400a620, 0x4212, 0xc000a34800, 0x4212, 0x4800, 0x0, 0x0, 0x0, 0xc0052e67e0, 0xc00930fa38)
	/usr/local/go/src/net/http/server.go:1607 +0x30a
net/http.(*response).Write(0xc00400a620, 0xc000a34800, 0x4212, 0x4800, 0x415f1b, 0xc00930fac8, 0xaa79ac1e)
	/usr/local/go/src/net/http/server.go:1565 +0x56
github.com/gorilla/handlers.(*responseLogger).Write(0xc008027d00, 0xc000a34800, 0x4212, 0x4800, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/gorilla/handlers@v1.4.2/handlers.go:59 +0x51
github.com/ava-labs/avalanchego/vms/rpcchainvm/ghttp/gresponsewriter.(*Server).Write(0xc00028e360, 0x15e08a0, 0xc00957a570, 0xc0047f29b0, 0xc00028e360, 0xc00957a570, 0xc002610ba0)
	/go/src/github.com/ava-labs/avalanchego/vms/rpcchainvm/ghttp/gresponsewriter/writer_server.go:49 +0x159
github.com/ava-labs/avalanchego/vms/rpcchainvm/ghttp/gresponsewriter/gresponsewriterproto._Writer_Write_Handler(0xedf3c0, 0xc00028e360, 0x15e08a0, 0xc00957a570, 0xc00500f9e0, 0x0, 0x15e08a0, 0xc00957a570, 0xc000a30000, 0x4248)
	/go/src/github.com/ava-labs/avalanchego/vms/rpcchainvm/ghttp/gresponsewriter/gresponsewriterproto/gresponsewriter.pb.go:561 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0018c1a00, 0x15ebac0, 0xc001345980, 0xc003ab0e00, 0xc0050cc960, 0x1ca1760, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0018c1a00, 0x15ebac0, 0xc001345980, 0xc003ab0e00, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xcc5
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0016cd2f0, 0xc0018c1a00, 0x15ebac0, 0xc001345980, 0xc003ab0e00)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
```

**Comment by sosedoff** [comment]
I'm not sure if this is related or not, but i've bumped `ulimit` on my test machine from Ubuntu's default 1024 to 65k and haven't seen any panics so far.

**Comment by aaronbuchwald** [comment]
This issue has been fixed by the above PR in avalanchego and will be part of the next release.
